version = 1
category = "programming"
last-updated = "2025-12-21"

[[models]]
id = "openai/gpt-5.2"

[[models]]
id = "google/gemini-3-pro-preview"

[[models]]
id = "z-ai/glm-4.7"

[[models]]
id = "minimax/minimax-m2.1"

[[models]]
id = "x-ai/grok-code-fast-1"

[[models]]
id = "xiaomi/mimo-v2-flash:free"

[[models]]
id = "kwaipilot/kat-coder-pro:free"

[[models]]
id = "mistralai/devstral-2512:free"

[[models]]
id = "openai/gpt-oss-120b:free"

[[models]]
id = "qwen/qwen3-coder:free"
